# {name} - Bukkit Plugin configuration file
# Copyright © {copyright.years} Visual Illusions Entertainment
name: {name}
main: {bukkit.main.class}
version: {plugin.version}
author: Visual Illusions Entertainment
website: {wiki}

# Visual Illusions Specific Stuff
developers: {devs}
build.number: {build}
build.time: {build.time}
program.status: {program.status}
version.check.url: {version.check.url}
issues.url: {issues}
copyright.years: {copyright.years}
# # #

commands:
  search:
    description: Search command
    usage: /search <item|block> - Search item or block
    permission: searchids.search
  searchids:
    description: SearchIds information command
    usages: /searchids

permissions:
  searchids.search:
    description: Gives access to Search
    default: op
